# Generated by Django 4.2.2 on 2024-02-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("gamefile", models.FileField(upload_to="")),
                ("board", models.CharField(max_length=10)),
                ("pot", models.PositiveIntegerField()),
                ("stack", models.PositiveIntegerField()),
                ("hero_is_oop", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_hole", models.CharField(max_length=5)),
                ("hero_is_oop", models.BooleanField()),
                ("tree", models.JSONField()),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trainer.spot"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["spot"], name="trainer_han_spot_id_38a314_idx")
                ],
            },
        ),
    ]
