# Generated by Django 4.0.4 on 2023-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoldupHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winamax_id', models.CharField(max_length=200, unique=True)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=40)),
                ('played_at', models.DateTimeField()),
                ('holdup', models.PositiveSmallIntegerField()),
                ('hero_position', models.SmallIntegerField(null=True)),
                ('hero_hole', models.CharField(max_length=5, null=True)),
                ('hero_net', models.DecimalField(decimal_places=2, max_digits=40, null=True)),
                ('hero_showdown', models.IntegerField(null=True)),
                ('hero_all_in_adjusted', models.FloatField(null=True)),
                ('winning_hand', models.IntegerField(null=True)),
                ('rake', models.DecimalField(decimal_places=2, max_digits=40)),
                ('log', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='holduphand',
            index=models.Index(fields=['winamax_id'], name='tracker_hol_winamax_d6d758_idx'),
        ),
        migrations.AddIndex(
            model_name='holduphand',
            index=models.Index(fields=['limit'], name='tracker_hol_limit_61bbef_idx'),
        ),
        migrations.AddIndex(
            model_name='holduphand',
            index=models.Index(fields=['played_at'], name='tracker_hol_played__1d3f36_idx'),
        ),
        migrations.AddIndex(
            model_name='holduphand',
            index=models.Index(fields=['holdup'], name='tracker_hol_holdup_7462fb_idx'),
        ),
    ]
