# Generated by Django 4.0.4 on 2023-02-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holduphand',
            name='action',
            field=models.TextField(null=True),
        ),
    ]
