# Generated by Django 4.0.4 on 2023-04-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_holduphand_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='holduphand',
            name='hero_hole_token',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
